export const CONTACTS = [
  {
    id: 0,
    firstName: "Sarah",
    lastName: "Liu",
    phone: "+1 223-456-789",
    email: "sarahli@outlook.com",
  },
  {
    id: 1,
    firstName: "Alice",
    lastName: "Cooper",
    phone: "+1 223-456-789",
    email: "alicooper@yahoo.com",
  },
  {
    id: 2,
    firstName: "Aman",
    lastName: "Saigal",
    phone: "+1 223-456-789",
    email: "saiman@gmail.com",
  },
  {
    id: 3,
    firstName: "Brett",
    lastName: "Paul",
    phone: "+1 223-456-789",
    email: "paulbretty@outlook.com",
  },
  {
    id: 4,
    firstName: "Robert",
    lastName: "James",
    phone: "+1 223-456-789",
    email: "jamesrob@gmail.com",
  },
  {
    id: 5,
    firstName: "Mary",
    lastName: "Patricia",
    phone: "+1 223-456-789",
    email: "mpatry@rediff.com",
  },
  {
    id: 6,
    firstName: "John",
    lastName: "Michael",
    phone: "+1 223-456-789",
    email: "mijo97@outlook.com",
  },
  {
    id: 7,
    firstName: "Matthew",
    lastName: "Mark",
    phone: "+1 223-456-789",
    email: "mattmar@rediff.com",
  },
  {
    id: 8,
    firstName: "Kevin",
    lastName: "Hu",
    phone: "+1 223-456-789",
    email: "hu.kevin@outlook.com",
  },
  {
    id: 9,
    firstName: "Lisa",
    lastName: "Betty",
    phone: "+1 223-456-789",
    email: "bet_li@yahoo.com",
  },
  {
    id: 10,
    firstName: "Renee",
    lastName: "Dennis",
    phone: "+1 223-456-789",
    email: "redennis@gmail.com",
  },
  {
    id: 11,
    firstName: "Nancy",
    lastName: "Sandra",
    phone: "+1 223-456-789",
    email: "sandy.nan2@outlook.com",
  },
  {
    id: 12,
    firstName: "Sarah",
    lastName: "Ryan",
    phone: "+1 223-456-789",
    email: "ry_sarah@gmail.com",
  },
];
